import type { Metadata } from "next";
import "./globals.scss";
import { Space_Grotesk, Orbitron } from "next/font/google";

import Sidebar from "@/components/layouts/sideBar/Sidebar";
import Footer from "@/components/layouts/footer/Footer";

const spaceGrotesk = Space_Grotesk({
  subsets: ["latin"],
  variable: "--font-space-grotesk",
});

const orbitron = Orbitron({
  subsets: ["latin"],
  variable: "--font-orbitron",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${spaceGrotesk.variable} ${orbitron.variable}`} data-scroll-behavior="smooth">
      <body>
        <div className="layout">
          <Sidebar />
          <div className="layout__content">
            {children}
            <Footer />
          </div>
        </div>
      </body>
    </html>
  );
}
